# Generated by Django 4.1.4 on 2022-12-08 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('subcategories', '0002_subcategory_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='categories.category'),
        ),
    ]
