# Generated by Django 4.1.4 on 2022-12-16 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='subcategories.subcategory'),
        ),
    ]
