# Generated by Django 4.1.4 on 2022-12-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_condition_listing'),
        ('listings', '0002_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='conditions.condition'),
            preserve_default=False,
        ),
    ]
