# Generated by Django 4.1.4 on 2022-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
