# Generated by Django 4.1.4 on 2022-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
