# Generated by Django 4.1.4 on 2022-12-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='subcategory',
        ),
    ]
