# Generated by Django 4.1.4 on 2022-12-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0001_initial'),
        ('listings', '0005_remove_listing_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='subcategories.subcategory'),
            preserve_default=False,
        ),
    ]
