# Generated by Django 4.1.4 on 2022-12-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_price'),
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='listings.listing'),
            preserve_default=False,
        ),
    ]
