# Generated by Django 4.1.4 on 2022-12-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_condition_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='listing',
        ),
    ]
